// src/assets.ts

// Centralized asset management for images, videos, and other static files.
// This makes it easy to update assets in one place and prepares for a future CMS.
export const ASSETS = {
  // Logos
  LOGO_DARK: 'https://raw.githubusercontent.com/devoncasa/Tempa123-Asset/main/Tempa-logo-dark-small.webp',
  LOGO_WHITE_FOOTER: 'https://raw.githubusercontent.com/devoncasa/Tempa123-Asset/main/images/logos/Tempa-logo-white-footer-small.webp',

  // Videos
  HERO_VIDEO: 'https://raw.githubusercontent.com/devoncasa/Tempa123-Asset/main/tempa123-motion-webpage-vid2.mp4',

  // Page Specific Images
  ABOUT_PAGE: {
    HERO: 'https://raw.githubusercontent.com/devoncasa/Tempa123-Asset/main/images/about/about-hero.webp',
    WHY_WE_EXIST: 'https://raw.githubusercontent.com/devoncasa/Tempa123-Asset/main/images/about/why-we-exist.webp',
    FOUNDER: 'https://raw.githubusercontent.com/devoncasa/Tempa123-Asset/main/images/about/founder.webp',
    WHAT_WE_OFFER: 'https://raw.githubusercontent.com/devoncasa/Tempa123-Asset/main/images/about/what-we-offer.webp',
    PERFORMANCE_ENGINE: 'https://raw.githubusercontent.com/devoncasa/Tempa123-Asset/main/images/about/performance-engine.webp',
  },

  LINE_ORDERING_KIT: {
      SHOP_HERO: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1000&q=80',
      MENU_BOILED_CHICKEN: 'https://images.unsplash.com/photo-1626084059905-4ac6e36872a8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
      MENU_FRIED_CHICKEN: 'https://images.unsplash.com/photo-1599499801123-7790b50a2f76?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
      MENU_MIXED_CHICKEN: 'https://images.unsplash.com/photo-1625944230153-a19bceb3a3c6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=800&q=80',
      BANK_LOGOS: {
        BBL: 'https://raw.githubusercontent.com/devoncasa/Tempa123-Asset/main/images/line-kit/bbl.webp',
        BAY: 'https://raw.githubusercontent.com/devoncasa/Tempa123-Asset/main/images/line-kit/bay.webp',
        CIMB: 'https://raw.githubusercontent.com/devoncasa/Tempa123-Asset/main/images/line-kit/cimb.webp',
        KBANK: 'https://raw.githubusercontent.com/devoncasa/Tempa123-Asset/main/images/line-kit/kbank.webp',
        KKP: 'https://raw.githubusercontent.com/devoncasa/Tempa123-Asset/main/images/line-kit/kkp.webp',
        KTB: 'https://raw.githubusercontent.com/devoncasa/Tempa123-Asset/main/images/line-kit/ktb.webp',
        SCB: 'https://raw.githubusercontent.com/devoncasa/Tempa123-Asset/main/images/line-kit/scb.webp',
        TTB: 'https://raw.githubusercontent.com/devoncasa/Tempa123-Asset/main/images/line-kit/ttb.webp',
      }
  },

  INSPIRATION_GALLERY: {
      VIDEO_POSTER: 'https://raw.githubusercontent.com/devoncasa/Tempa123-Asset/main/images/logos/tempa123-flying-banner-logo.webp',
      VIDEO: 'https://raw.githubusercontent.com/devoncasa/Tempa123-Asset/main/images/logos/tempa123-photo-gallery-002.mp4',
  },
  
  // Parallax background images used across the site
  BACKGROUND_IMAGES: [
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-001.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-002.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-003.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-004.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-005.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-006.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-007.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-008.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-009.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0010.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0011.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0012.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0013.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0014.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0015.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0016.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0017.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0018.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0019.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0020.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0021.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0022.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0023.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0024.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0025.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0026.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0027.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0028.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0029.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0030.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0031.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0032.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0033.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0034.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0035.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0036.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0037.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0038.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0039.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0040.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0041.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0042.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0043.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0044.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0045.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0046.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0047.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0048.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0049.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0050.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0051.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0052.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0053.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0054.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0055.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0056.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0057.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0058.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0059.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0060.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0061.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0062.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0063.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0064.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0065.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0066.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0067.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0068.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0069.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0070.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0071.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0072.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0073.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0074.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0075.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0076.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0077.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0078.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0079.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0080.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0081.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0082.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0083.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0084.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0085.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0086.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0087.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0088.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0089.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0090.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0091.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0092.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0093.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0094.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0095.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0096.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0097.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0098.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-0099.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-00100.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-00101.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-00102.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-00103.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-00104.jpeg',
    'https://cdn.jsdelivr.net/gh/devoncasa/Tempa123-Asset@main/section-background/tempa123-section-background-light-00105.jpeg',
  ],
};